# ===========================================
# PVs e PVCs Est√°ticos - Sempre usam as mesmas pastas no NFS
# ===========================================

# PVC para Jenkins
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-pvc
  namespace: portainer
  labels:
    app.kubernetes.io/name: portainer
    app.kubernetes.io/component: portainer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-static
  volumeName: portainer-pv
  resources:
    requests:
      storage: 10Gi
---
# PVC para Jenkins
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-config-pvc
  namespace: romm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-static
  volumeName: romm-config-pv
  resources:
    requests:
      storage: 1Gi
---
# PVC para PostgreSQL do SonarQube
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-library-pvc
  namespace: romm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-static
  resources:
    requests:
      storage: 100Gi
---
# PVC para Harbor Registry
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-resources-pvc
  namespace: romm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-static
  volumeName: romm-resources-pv
  resources:
    requests:
      storage: 10Gi
---
# PVC para SonarQube
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-assets-pvc
  namespace: romm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-static
  resources:
    requests:
      storage: 5Gi
---
# PVC para SonarQube
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-mariadb-pvc
  namespace: romm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-static
  resources:
    requests:
      storage: 10Gi
---
# PVC para Harbor JobService
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-static
  volumeName: jellyfin-config-pv
  resources:
    requests:
      storage: 5Gi
---
# PVC para Harbor Database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-static
  volumeName: jellyfin-media-pv
  resources:
    requests:
      storage: 100Gi
---
# PVC para Harbor Redis
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-static
  volumeName: jellyfin-cache-pv
  resources:
    requests:
      storage: 10Gi
---
# PVC para Harbor Trivy
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meu-site-mongodb-pvc
  namespace: meu-site
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: meu-site
    meta.helm.sh/release-namespace: meu-site
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-static
  volumeName: meu-site-mongodb-pv
  resources:
    requests:
      storage: 8Gi
---
# PVC para Harbor Trivy
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-static
  volumeName: pihole-pv
  resources:
    requests:
      storage: 1Gi
---
# PVC para Harbor Trivy
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-pvc
  namespace: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-static
  volumeName: vaultwarden-pv
  resources:
    requests:
      storage: 10Gi